// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "使用邮箱和密码登录。返回 access_token（有效期15分钟）和 refresh_token（有效期30天）。access_token 用于调用其他接口，refresh_token 用于在 access_token 过期后换取新令牌。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.AuthResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数格式错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "邮箱或密码错误 或 账号已被封禁",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "使当前 refresh_token 永久失效。登出后 access_token 仍在有效期内可使用（最多15分钟），客户端应同时清除本地存储的所有 token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "要失效的 Refresh Token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RefreshTokenInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登出成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "参数格式错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录或 token 已过期",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "当 access_token 过期时，使用 refresh_token 换取新的 token 对。采用 Rotation 策略，每次调用后旧的 refresh_token 立即失效，请使用新返回的 refresh_token 替换本地存储。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "刷新 Access Token",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RefreshTokenInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功，返回新的 token 对",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.AuthResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数格式错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "refresh_token 无效、已过期或已被使用",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "使用邮箱和密码创建新账号。注册成功后直接返回 token 对，无需再次调用登录接口。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "注册成功，返回 token 对和用户信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.AuthResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数格式错误 或 邮箱已被注册",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/couple/bind": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "输入对方生成的邀请码完成伴侣绑定。绑定成功后，双方可以共享亲密记录、心愿清单等数据。每个用户同时只能有一段有效的伴侣关系。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "伴侣"
                ],
                "summary": "绑定伴侣",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "邀请码",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.BindInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "绑定成功，返回伴侣信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.CoupleInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "邀请码无效/已过期/不能绑定自己/已有伴侣",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/couple/info": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的伴侣关系信息，包括对方的用户资料和绑定时间",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "伴侣"
                ],
                "summary": "获取伴侣信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "伴侣信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.CoupleInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "暂无伴侣关系",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/couple/invite": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "生成一个6位邀请码，有效期15分钟。将邀请码分享给伴侣，对方通过邀请码完成绑定。如果已有未使用的邀请码，调用此接口会刷新邀请码并重置有效期。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "伴侣"
                ],
                "summary": "生成邀请码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "邀请码信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.InviteCodeResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "已有伴侣，无法生成邀请码",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/couple/unbind": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "解除与当前伴侣的绑定关系。解除后历史记录仍然保留，但不再共享新数据。此操作不可撤销。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "伴侣"
                ],
                "summary": "解除伴侣关系",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "解除成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "暂无伴侣关系",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/records/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建一条新的亲密记录。必须先绑定伴侣才能创建记录。备注内容请在客户端加密后传入密文，后端不会解密存储。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "亲密记录"
                ],
                "summary": "创建记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "记录内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateRecordInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Record"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或未绑定伴侣",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/records/delete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "软删除一条亲密记录，删除后不可恢复。只能删除自己伴侣关系下的记录。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "亲密记录"
                ],
                "summary": "删除记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "记录 ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RecordIDInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误或记录不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/records/detail": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取单条亲密记录的详细信息，包括关联的标签和姿势。只能查看自己伴侣关系下的记录。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "亲密记录"
                ],
                "summary": "获取记录详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "记录 ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RecordIDInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "记录详情",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Record"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "记录不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/records/list": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页获取当前伴侣的亲密记录列表，按发生时间倒序排列。支持按年、月过滤。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "亲密记录"
                ],
                "summary": "获取记录列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "查询条件",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.RecordListInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "记录列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.RecordListResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/records/positions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取可用的姿势列表，包括系统预设姿势和当前伴侣自定义姿势",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "亲密记录"
                ],
                "summary": "获取姿势列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "姿势列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Position"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/records/tags": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取可用的标签列表，包括系统预设标签和当前伴侣自定义标签。type 传 LOCATION 获取地点标签，传 ACTIVITY 获取活动标签。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "亲密记录"
                ],
                "summary": "获取标签列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "标签类型",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.GetTagsInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "标签列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Tag"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/records/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新一条亲密记录，只传需要修改的字段。标签和姿势列表为全量替换，传空数组表示清除所有关联。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "亲密记录"
                ],
                "summary": "更新记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "要更新的内容（需包含 id 字段）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateRecordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新后的记录",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Record"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或记录不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/password/change": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改当前登录用户的密码，需要提供旧密码验证身份。修改成功后所有设备强制下线",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "旧密码和新密码",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.ChangePasswordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误或旧密码不正确",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录或 token 已过期",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/profile/get": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户的详细信息，包括昵称、头像、生日等",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取个人信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未登录或 token 已过期",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/profile/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新当前登录用户的昵称、头像、生日等，只传需要修改的字段",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "更新个人信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "要更新的字段",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateProfileInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新后的用户信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数格式错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未登录或 token 已过期",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.BindInput": {
            "type": "object",
            "required": [
                "invite_code"
            ],
            "properties": {
                "invite_code": {
                    "description": "InviteCode 对方生成的6位邀请码",
                    "type": "string",
                    "example": "A3KP7X"
                }
            }
        },
        "handler.GetTagsInput": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "description": "Type 标签类型：LOCATION（地点标签）或 ACTIVITY（活动标签）",
                    "type": "string",
                    "enum": [
                        "LOCATION",
                        "ACTIVITY"
                    ],
                    "example": "LOCATION"
                }
            }
        },
        "handler.RecordIDInput": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "ID 记录唯一标识",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "handler.RefreshTokenInput": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "description": "RefreshToken 登录时获得的长期刷新令牌",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "model.Position": {
            "type": "object",
            "properties": {
                "couple_id": {
                    "description": "CoupleID 所属伴侣 ID，系统姿势此字段为空",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt 创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "ID 姿势唯一标识",
                    "type": "string"
                },
                "is_system": {
                    "description": "IsSystem 是否为系统预设姿势",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name 姿势名称",
                    "type": "string",
                    "example": "传教士"
                }
            }
        },
        "model.Record": {
            "type": "object",
            "properties": {
                "couple_id": {
                    "description": "CoupleID 所属伴侣关系 ID，关联 couples 表",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt 记录创建时间",
                    "type": "string"
                },
                "created_by_id": {
                    "description": "CreatedByID 创建此记录的用户 ID",
                    "type": "string"
                },
                "duration_mins": {
                    "description": "DurationMins 持续时长（分钟），可选",
                    "type": "integer",
                    "example": 30
                },
                "happened_at": {
                    "description": "HappenedAt 实际发生时间，支持回填历史记录",
                    "type": "string"
                },
                "id": {
                    "description": "ID 记录唯一标识，UUID 格式",
                    "type": "string"
                },
                "mood": {
                    "description": "Mood 心情评分 1-5，1最差5最好，可选",
                    "type": "integer",
                    "example": 4
                },
                "note_encrypted": {
                    "description": "NoteEncrypted 备注内容，客户端加密后存储的密文，后端不解密",
                    "type": "string"
                },
                "positions": {
                    "description": "Positions 关联的姿势列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Position"
                    }
                },
                "satisfaction": {
                    "description": "Satisfaction 满意度评分 1-5，1最差5最好，可选",
                    "type": "integer",
                    "example": 5
                },
                "tags": {
                    "description": "Tags 关联的标签列表（地点、活动）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Tag"
                    }
                },
                "updated_at": {
                    "description": "UpdatedAt 记录最后更新时间",
                    "type": "string"
                }
            }
        },
        "model.Tag": {
            "type": "object",
            "properties": {
                "couple_id": {
                    "description": "CoupleID 所属伴侣 ID，系统标签此字段为空",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt 创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "ID 标签唯一标识",
                    "type": "string"
                },
                "is_system": {
                    "description": "IsSystem 是否为系统预设标签，系统标签不可删除",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name 标签名称，如\"家里\"、\"酒店\"、\"浪漫\"",
                    "type": "string",
                    "example": "家里"
                },
                "type": {
                    "description": "Type 标签类型：LOCATION（地点）或 ACTIVITY（活动）",
                    "type": "string",
                    "example": "LOCATION"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "description": "AvatarURL 用户头像图片地址",
                    "type": "string",
                    "example": "https://cdn.example.com/avatar.jpg"
                },
                "birthday": {
                    "description": "Birthday 用户生日，用于计算星座、年龄等",
                    "type": "string",
                    "example": "1995-06-15T00:00:00Z"
                },
                "created_at": {
                    "description": "CreatedAt 账号创建时间，由数据库自动填充",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "email": {
                    "description": "Email 用户邮箱，唯一，可用于登录，注册时必填",
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "description": "ID 用户唯一标识，UUID 格式，由数据库自动生成",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_blocked": {
                    "description": "IsBlocked 账号是否被管理员封禁，封禁后无法登录",
                    "type": "boolean",
                    "example": false
                },
                "is_verified": {
                    "description": "IsVerified 邮箱或手机号是否已通过验证",
                    "type": "boolean",
                    "example": false
                },
                "nickname": {
                    "description": "Nickname 用户昵称，显示在界面上的名称",
                    "type": "string",
                    "example": "小明"
                },
                "phone": {
                    "description": "Phone 用户手机号，唯一，可用于登录，可选",
                    "type": "string",
                    "example": "+8613800138000"
                },
                "updated_at": {
                    "description": "UpdatedAt 账号最后更新时间，由数据库自动维护",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code 业务状态码，0 表示成功，其他值表示错误",
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "description": "Data 响应数据，失败时为 null"
                },
                "message": {
                    "description": "Message 提示信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "service.AuthResult": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "AccessToken 短期访问令牌，有效期15分钟\n调用需要登录的接口时放在 Header: Authorization: Bearer \u003caccess_token\u003e",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refresh_token": {
                    "description": "RefreshToken 长期刷新令牌，有效期30天\nAccess Token 过期后，用此 token 换取新的 token 对\n请安全存储，不要暴露",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "description": "User 当前登录的用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.User"
                        }
                    ]
                }
            }
        },
        "service.ChangePasswordInput": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "description": "NewPassword 新密码，最少8位",
                    "type": "string",
                    "minLength": 8,
                    "example": "newpassword456"
                },
                "old_password": {
                    "description": "OldPassword 当前使用的旧密码，用于验证身份",
                    "type": "string",
                    "example": "oldpassword123"
                }
            }
        },
        "service.CoupleInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt 绑定时间",
                    "type": "string"
                },
                "id": {
                    "description": "ID 伴侣关系唯一 ID",
                    "type": "string"
                },
                "partner": {
                    "description": "Partner 对方的用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.User"
                        }
                    ]
                }
            }
        },
        "service.CreateRecordInput": {
            "type": "object",
            "required": [
                "happened_at"
            ],
            "properties": {
                "duration_mins": {
                    "description": "DurationMins 持续时长（分钟），可选",
                    "type": "integer",
                    "example": 30
                },
                "happened_at": {
                    "description": "HappenedAt 实际发生时间，支持回填过去的记录，格式 RFC3339",
                    "type": "string",
                    "example": "2024-01-15T20:00:00Z"
                },
                "mood": {
                    "description": "Mood 心情评分 1-5，1最差5最好，可选",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 4
                },
                "note_encrypted": {
                    "description": "NoteEncrypted 备注密文，由客户端加密后传入，后端原样存储不解密",
                    "type": "string",
                    "example": "U2FsdGVkX1..."
                },
                "position_ids": {
                    "description": "PositionIDs 姿势 ID 列表，可同时关联多个姿势",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['uuid1']"
                    ]
                },
                "satisfaction": {
                    "description": "Satisfaction 满意度评分 1-5，1最差5最好，可选",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 5
                },
                "tag_ids": {
                    "description": "TagIDs 标签 ID 列表，可同时关联多个标签",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['uuid1'",
                        "'uuid2']"
                    ]
                }
            }
        },
        "service.InviteCodeResult": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "description": "ExpiresAt 邀请码过期时间，过期后需要重新生成",
                    "type": "string"
                },
                "invite_code": {
                    "description": "InviteCode 6位邀请码，有效期15分钟",
                    "type": "string",
                    "example": "A3KP7X"
                }
            }
        },
        "service.LoginInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "Email 登录邮箱",
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "description": "Password 登录密码",
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "service.RecordListInput": {
            "type": "object",
            "properties": {
                "month": {
                    "description": "Month 按月份过滤，不传则返回全部，需要和 year 一起使用",
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1,
                    "example": 1
                },
                "page": {
                    "description": "Page 页码，从 1 开始，默认 1",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "page_size": {
                    "description": "PageSize 每页数量，默认 20，最大 50",
                    "type": "integer",
                    "maximum": 50,
                    "minimum": 1,
                    "example": 20
                },
                "year": {
                    "description": "Year 按年份过滤，不传则返回全部",
                    "type": "integer",
                    "example": 2024
                }
            }
        },
        "service.RecordListResult": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "List 记录列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Record"
                    }
                },
                "page": {
                    "description": "Page 当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "PageSize 每页数量",
                    "type": "integer"
                },
                "total": {
                    "description": "Total 总记录数",
                    "type": "integer"
                }
            }
        },
        "service.RegisterInput": {
            "type": "object",
            "required": [
                "email",
                "nickname",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "Email 注册邮箱，必须是合法的邮箱格式，注册后作为登录账号",
                    "type": "string",
                    "example": "user@example.com"
                },
                "nickname": {
                    "description": "Nickname 用户昵称，显示在 App 界面，2到20个字符",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2,
                    "example": "小明"
                },
                "password": {
                    "description": "Password 登录密码，最少8位，建议包含字母和数字",
                    "type": "string",
                    "minLength": 8,
                    "example": "password123"
                }
            }
        },
        "service.UpdateProfileInput": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "description": "AvatarURL 头像图片地址，需要先通过上传接口获得 URL 再传入",
                    "type": "string",
                    "example": "https://cdn.example.com/avatar.jpg"
                },
                "birthday": {
                    "description": "Birthday 生日，格式 RFC3339",
                    "type": "string",
                    "example": "1995-06-15T00:00:00Z"
                },
                "nickname": {
                    "description": "Nickname 昵称，2到20个字符",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2,
                    "example": "小红"
                }
            }
        },
        "service.UpdateRecordInput": {
            "type": "object",
            "properties": {
                "duration_mins": {
                    "description": "DurationMins 修改时长",
                    "type": "integer",
                    "example": 45
                },
                "happened_at": {
                    "description": "HappenedAt 修改发生时间",
                    "type": "string",
                    "example": "2024-01-15T21:00:00Z"
                },
                "mood": {
                    "description": "Mood 修改心情评分",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 3
                },
                "note_encrypted": {
                    "description": "NoteEncrypted 修改备注密文",
                    "type": "string"
                },
                "position_ids": {
                    "description": "PositionIDs 重新设置姿势列表（全量替换）",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "satisfaction": {
                    "description": "Satisfaction 修改满意度评分",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 4
                },
                "tag_ids": {
                    "description": "TagIDs 重新设置标签列表（全量替换）",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "登录后将 access_token 填入此处，格式：Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Bondy API",
	Description:      "Bondy 伴侣亲密记录 App 后端接口文档。调用需要登录的接口时，在 Header 中加入 Authorization: Bearer <access_token>",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
